name: Deployments
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'https://www.google.com.br'
    needs: build   
    steps:
      - name: Run a one-line script
        run: echo deploy dev
        
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'https://www.google.com.br'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo deploy hml
        
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'https://www.google.com.br'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo deploy prd
